[고현영] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/31-westagram-backend-1-team pull request #11
Opened 2022-03-18 04:57 UTC by hy6652

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-회원가입 view 생성
		 
## 수정 사항들 자세한 내용
- SignUpView 생성
- urls.py 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-18 05:12 UTC, bigfanoftim requested changes

2022-03-18 05:12 UTC, bigfanoftim commented on students/hyunyoung/users/views.py
> +from users.models import User
import문 순서를 잘 지켜서 만들어주세요.
아래와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

(python convention 문서 참고해주세요.)

```python
# 파이썬 built-in 모듈
import json
import re

# 외부 모듈
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```
```suggestion
from django.http  import JsonResponse
from django.views import View

from users.models import User
```

2022-03-18 05:12 UTC, bigfanoftim commented on students/hyunyoung/users/views.py
> +                return JsonResponse({'message':'PASSWORD FORM ERROR'}, status=400)
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.
굳이 `compile()`하여 패턴 객체를 변수에 할당하고 활용할 필요없이 바로 조건문에서 판별하면 됩니다.

```python
import re

from django.core.exceptions import ValidationError

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

    if not re.match(REGEX_EMAIL, value):
        return JsonResponse(...)

    if not re.match(REGEX_EMAIL, value):
        return JsonResponse(...)
```

2022-03-18 05:12 UTC, bigfanoftim commented on students/hyunyoung/users/urls.py
> +from users.views import SignUpView
```suggestion
from django.urls import path

from users.views import SignUpView
```

2022-03-18 05:12 UTC, bigfanoftim commented on students/hyunyoung/users/views.py
> +            if users:
굳이 두 줄로 나눠 작성할 필요가 없어보입니다. 한 줄로 줄여보세요!

2022-03-18 05:12 UTC, bigfanoftim commented on students/hyunyoung/westagram/urls.py
> +    path('', include('users.urls'))
path가 불분명합니다. 이렇게 작성하셨다면 다른 앱이 추가되었을때는 어떻게 처리해야할까요?
```python
    path('', include('users.urls')),
    path('', include('products.urls')),
```

2022-03-18 05:12 UTC, bigfanoftim commented on students/hyunyoung/users/views.py
> +                return JsonResponse({'message':'this email already exists'}, status=400)
위에서는 에러 메세지를 대문자로, 여기서는 소문자로 작성하셨네요.
보다 명확하게 하나의 기준으로 통일해주세요.

2022-03-18 06:27 UTC, hy6652 commented
피드백 반영해서 수정했습니다

2022-03-18 06:33 UTC, bigfanoftim requested changes

2022-03-18 06:33 UTC, bigfanoftim commented on students/hyunyoung/users/views.py
> +                if email is '':
`request.body`에 email이 없을때 어떤 오류가 나는지 직접 확인하시고 except에서 에러를 잡아주세요!
```suggestion
```

2022-03-18 06:33 UTC, bigfanoftim commented on students/hyunyoung/westagram/urls.py
> +    path('users/', include('users.urls'))
- `main URLconf`에서는 가독성을 위해 `/`를 전부 지워주세요.
- `include`로 라우팅되는 `urls.py`에서 `/`를 추가하여 작성해주세요.
```python
# users/urls.py
    path('/signup', ...)
```

2022-03-18 07:53 UTC, hy6652 commented
피드백 사항 수정 했습니다!

2022-03-19 14:18 UTC, bigfanoftim requested changes

2022-03-19 14:18 UTC, bigfanoftim commented on students/hyunyoung/users/models.py
>  # Create your models here.
불필요한 주석은 지워주세요~

2022-03-19 14:18 UTC, bigfanoftim commented on students/hyunyoung/users/views.py
> +                raise KeyError
현영님 KeyError를 본인이 직접 raise하는게 아니라 어떤 경우에 KeyError가 나오는지 직접 테스트해보시고 try except문에서 잡아주세요

2022-03-19 16:12 UTC, hy6652 commented
수정했습니다!

2022-03-21 05:09 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-21 05:09 UTC, merged