[김수훈] Mission 2 : 모델링
wecode-bootcamp-korea/31-westagram-backend-1-team pull request #8
Opened 2022-03-17 06:57 UTC by suhun96

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- models.py 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-17 07:31 UTC, bigfanoftim requested changes
`model` 클래스 작성하시면 migrations 파일도 생성 후 같이 푸시해주세요~

2022-03-17 07:31 UTC, bigfanoftim commented on students/suhun/users/models.py
> +    email       = models.EmailField(max_length=245)
`email field`에 `unique` 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
공식 문서에서 그 방법을 찾아보고 적용해주세요.

2022-03-17 07:31 UTC, bigfanoftim commented on students/suhun/users/models.py
> +    phone       = models.IntegerField(max_length=120)
보통 전화번호는 `CharField`를 사용해서 관리하므로 Field를 수정해주세요!

예) +82 010-7444-2659

2022-03-18 01:19 UTC, kyeongraekim requested changes

2022-03-18 01:19 UTC, kyeongraekim commented on students/suhun/users/models.py
> +    update_at     = models.DateField(auto_now_add=True, auto_now= False)
- updated_at 변수명 부분도 위 created_at 처럼 올바른 영문법을 사용하여 과거형으로 맞추어주세요~

- auto_now_add와 auto_now의 속성 차이를 다시 한 번 확인해주셔서 created_at과 updated_at간 서로 다른 속성을 어떻게 부여해야할지 한 번 다시 고민해주세요!~

2022-03-18 01:32 UTC, suhun96 commented on students/suhun/users/models.py
> +    update_at     = models.DateField(auto_now_add=True, auto_now= False)
넵 알겠습니다!

2022-03-18 01:49 UTC, bigfanoftim requested changes
수훈님 현재 `Mission 2 : 모델링`에 해당하는 수정 사항들만 PR에 올라와야 하는데, `hojun` 디렉토리를 지운 것, View 작성 등 불필요한 수정 사항들이 너무 많이 올라와있습니다. PR 올리시고 해당 PR의 `Files changed`를 한 번 더 확인하세요.

2022-03-18 04:58 UTC, closed without merging