[김대현] Mission 2 : 모델링
wecode-bootcamp-korea/31-westagram-backend-1-team pull request #9
Opened 2022-03-17 07:02 UTC by kdh10806

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- User 모델 추가
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-17 07:38 UTC, bigfanoftim requested changes

2022-03-17 07:38 UTC, bigfanoftim commented on students/daehyun/westargram/users/models.py
> +    email       = models.CharField(max_length=30)
`email field`에 `unique` 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
공식 문서에서 그 방법을 찾아보고 적용해주세요.
```suggestion
```

2022-03-17 07:38 UTC, bigfanoftim commented on students/daehyun/westargram/users/models.py
> +    password    = models.CharField(max_length=30)
`password property`는 나중에 해시(암호화)된 비밀번호 길이를 고려해서 넉넉하게 100 이상으로 설정해주세요.
```suggestion
```

2022-03-17 07:38 UTC, bigfanoftim commented on students/daehyun/westargram/users/models.py
> +    phonenumber = models.PhoneNumberField((""))
보통 전화번호는 `CharField`를 사용해서 관리하므로 Field를 수정해주세요!

예) +82 010-7444-2659
```suggestion
```

2022-03-17 07:38 UTC, bigfanoftim commented on students/daehyun/westargram/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```
```suggestion

    
```

2022-03-17 07:58 UTC, kdh10806 commented on students/daehyun/westargram/users/models.py
> +
수정 요청 해주신 부분 수정했습니다.

2022-03-17 07:59 UTC, kdh10806 commented
수정 요청해주신 부분 수정 완료했습니다.

2022-03-18 01:17 UTC, kyeongraekim requested changes

2022-03-18 01:17 UTC, kyeongraekim commented on students/daehyun/westargram/users/models.py
> +    phonenumber = models.CharField(max_length=25)
제 3자의 가독성을 위해서 전화번호 변수명 관련 snake case를 이용하여 띄어쓰기를 표현해주세요~

2022-03-18 01:32 UTC, kdh10806 commented
전화번호 변수명 snake case로 변경했습니다.

2022-03-18 01:50 UTC, bigfanoftim requested changes
대현님 현재 PR은 `Mission 2 : 모델링`과 관련된 코드만 올라와야 합니다. view 관련 코드 다 지우고 다시 올려주세요.

2022-03-18 04:09 UTC, kdh10806 commented
view 관련 코드 삭제하고 다시 올렸습니다.

2022-03-18 04:59 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-18 05:00 UTC, merged